# Backstage override configuration for your local development environment
auth:
  environment: development
  session:
    secret: lKhugktHy0/FR9iJnMjRVlNSDfCGBYSAj8cESh6nchw=
  providers:
    ldap:
      development:
        ldapAuthenticationOptions:
          userSearchBase: ou=users,dc=company,dc=com
          usernameAttribute: uid

          adminDn: cn=admin,dc=company,dc=com
          adminPassword: admin

          ldapOpts:
            url: ldap://localhost:389
    guest: {}
    github:
      development:
        clientId: Ov23li7jQKZ4gAAYUqTq
        clientSecret: ec92ebbf9571ac04bb1cbe021d787c739a465913
        scope: "read:user,user:email"
argocd:
  appLocatorMethods:
    - type: config
      instances:
        - name: local
          url: http://34.180.8.42/
          token: ${ARGOCD_TOKEN}
          insecure: true
integrations:
  github:
    - host: github.com
      token: ${GITHUB_TOKEN}
