app:
  # Should be the same as backend.baseUrl when using the `app-backend` plugin.
  baseUrl: ${APP_BASE_URL}

backend:
  # Note that the baseUrl should be the URL that the browser and other clients
  # should use when communicating with the backend, i.e. it needs to be
  # reachable not just from within the backend host, but from all of your
  # callers. When its value is "http://localhost:7007", it's strictly private
  # and can't be reached by others.
  baseUrl: ${BACKEND_BASE_URL}
  # The listener can also be expressed as a single <host>:<port> string. In this case we bind to
  # all interfaces, the most permissive setting. The right value depends on your specific deployment.
  listen: ':7007'

  # config options: https://node-postgres.com/apis/client
  database:
    client: pg
    connection:
      host: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
      database: ${POSTGRES_DB}
      # https://node-postgres.com/features/ssl
      # you can set the sslmode configuration option via the `PGSSLMODE` environment variable
      # see https://www.postgresql.org/docs/current/libpq-ssl.html Table 33.1. SSL Mode Descriptions (e.g. require)
      # ssl:
      #   ca: # if you have a CA file and want to verify it you can uncomment this section
      #     $file: <file-path>/ca/server.crt

auth:
  environment: production
  session:
    secret: lKhugktHy0/FR9iJnMjRVlNSDfCGBYSAj8cESh6nchw=
  providers:
    ldap:
      production:
        ldapAuthenticationOptions:
          userSearchBase: ou=users,dc=company,dc=com
          usernameAttribute: uid

          adminDn: cn=admin,dc=company,dc=com
          adminPassword: test123

          ldapOpts:
            url: ldap://ldap-service.identity.svc.cluster.local:389

    github:
      production:
        clientId: Ov23li7jQKZ4gAAYUqTq
        clientSecret: ec92ebbf9571ac04bb1cbe021d787c739a465913
        scope: "read:user,user:email"
argocd:
  appLocatorMethods:
    - type: config
      instances:
        - name: local
          url: http://34.180.8.42/
          token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhcmdvY2QiLCJzdWIiOiJhZG1pbjphcGlLZXkiLCJuYmYiOjE3ODI5MDkwNDMsImlhdCI6MTc4MjkwOTA0MywianRpIjoiMzM0NzEwY2MtZjEyMC00YjE4LWFmNGItNGYzZWQ4ZGU3ZjAyIn0.PSvdAY6-67QF3gYYRgZnyzM12symkudasWcEeXjFUtU
          insecure: true

jenkins:
  instances:
    - name: default
      baseUrl: http://localhost:9090
      username: admin
      apiKey: ${JENKINS_TOKEN}

integrations:
  github:
    - host: github.com
      token:  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

sonarqube:
  baseUrl: https://sonarcloud.io
  apiKey: e0052ac925921d8055e8436bfb55085033e5a22a