---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: user-service
  description: User management service
  annotations:
    platform.io/jira-base-url: https://your-org.atlassian.net
    company.com/application: user-service
spec:
  type: service
  lifecycle: production
  owner: team-platform
  system: examples
  infrastructure:
    environments:
      - name: dev
        projectId: retail-dev-123
      - name: qa
        projectId: retail-qa-123
      - name: prod
        projectId: retail-prod-123
  platform:
    jiraId: USR-9876
    setupApproved: true
    businessUnit: Digital Experience
    appId: APP-9012
    supportTeam: identity-support
    tier: Silver
    environment: Production
    criticality: Medium
